---
- hosts: all
  become: true
  become_method: sudo
  vars:
  tasks:
    - name: install required packages
      apt: pkg={{ item }} state=latest update_cache=true
      with_items:
        - git
        - curl
        - htop
        - php5
        - php5-cli
        - php5-gd
        - php5-curl
    - name: Install Composer
      get_url:
        url=https://getcomposer.org/composer.phar
        dest=/usr/local/bin/composer
        mode=0755
        validate_certs=no
    - name: Tidy up the system
      shell: apt-get clean -y; apt-get autoremove -y;
    - name: make git ignore the filepermissions change
      shell: cd /var/www/html/; git config core.filemode false;
    - name: composer install
      composer:
        command=install
        working_dir=/var/www/html
